# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-08 11:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flex', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='process_id',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
